Added pull request template
Awesome-React-Modules/React-Dark pull request #16
Opened 2020-03-21 16:59 UTC by Aman-Codes

@AdityaSrivast Please review my pull request and do let me know if any changes are required.
Added pull_request_template.md
Closes: #14   
## Screenshots
### Pull request
![pull request](https://user-images.githubusercontent.com/54680709/77219120-858b1480-6b58-11ea-9336-e334f4c247f9.PNG)

2020-03-21 22:05 UTC, plxity approved these changes

2020-03-22 05:02 UTC, AdityaSrivast requested changes
@Aman-Codes add this file inside `PULL_REQUEST_TEMPLATE/` directory. Rest seems fine :+1:

2020-03-22 08:20 UTC, Aman-Codes commented
@AdityaSrivast Sir did the asked changes.

2020-03-22 14:04 UTC, AdityaSrivast approved these changes

2020-03-25 10:16 UTC, merged